- hosts: all
  become: yes
  # gather_subset: min
  gather_facts: true

  vars_files:
    - host_vars/remote_vars.yaml


  roles:
    - role: remote-common
    - role: remote-mount-volume
    - role: remote-install-docker
    - role: remote-docker-proxy